kraft:
  enabled: true
zookeeper:
  enabled: false


auth:
  enabled: false
allowPlaintextListener: true
listeners:
  client:
    protocol: PLAINTEXT
advertisedListeners:
  client:
    name: PLAINTEXT
    address: kafka.proving-system.svc.cluster.local
    port: 9092

broker:
  extraConfig:
    message.max.bytes: 52428800
    replica.fetch.max.bytes: 52428800
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1


controller:
  extraConfig:
    replica.fetch.max.bytes: 52428800
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1

global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

# Disable identity as part of the Camunda core
identity:
  enabled: false

# Disable keycloak
identityKeycloak:
  enabled: false

optimize:
  enabled: false

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi

zeebeGateway:
  replicas: 1

connectors:
  enabled: false

elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 15Gi
