apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topics
  namespace: proving-system
spec:
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: confluentinc/cp-kafka:latest
          command:
            - bash
            - -c
            - |
              kafka-topics --bootstrap-server camunda-kafka.proving-system.svc.cluster.local:9092 --create --if-not-exists --topic shipments --partitions 1 --replication-factor 1 && \
              kafka-topics --bootstrap-server camunda-kafka.proving-system.svc.cluster.local:9092 --create --if-not-exists --topic pcf-results --partitions 1 --replication-factor 1
      restartPolicy: OnFailure


